name: Release Please Automatic patch notes
on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  main:
    runs-on: ubuntu-20.04
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: simple
          package-name: jasm
          extra-files: |
                        src/GIMI-ModManager.WinUI/GIMI-ModManager.WinUI.csproj
